### ISSUE TITLE
Demo code from README.md not compiling - missing isWhitespace & CallbackToCssClasses

### ISSUE THREAD

**Issue by bloognoo** [vegardit/haxe-strings#6]
COMPILER OUTPUT:
Source/Main.hx:28: characters 16-28 : String has no field isWhitespace
Source/Main.hx:43: lines 43-51 : Identifier 'CallbackToCssClasses' is not part of hx.strings.AnsiToHtmlRenderMethod
Source/Main.hx:43: lines 43-51 : For optional function argument 'renderMethod'

BUILDING TO: Neko -64

VERSIONS: 
Haxe: 4.0.5
Haxe-strings: 5.2.4 from haxelib, current head of master
OpenFL: 8.9.5
OS: Peppermint Linux 10 Respin (Ubuntu 18.04.3)
IDE: Vim 8.2.121 w/ vaxe 

Attached: project files
[StringWiggle.zip](https://github.com/vegardit/haxe-strings/files/4114620/StringWiggle.zip)

**Comment by grepsuzette** [comment]
Ok the README.md example has a few typos/problems:

1. `"".isWhitespace()` is not supposed to work (that's a method of class Char, not String), so that line must be dropped.
2. The line with `ansiToHtml` was carelessly written by me. ~~CallbackToCssClasses~~ and ~~ANSIState~~ were improperly written. Instead the proper class names to use are `CssClassesCallback` and `hx.strings.AnsiState`. 

Lastly, and after all maybe that's what you want, your project seems to be using openfl. Maybe it will work for you but as I don't use it myself, I had to transform that to a regular `class Main { public static function main() { ... }` so it compiles.

Will issue a pull request shortly so that the README.md is updated with those changes.

**Comment by sebthom** [comment]
Thanks for the PR!

**Comment by bloognoo** [comment]
Thank you all.
